# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a8a647a670e1dfbaa4ac90501929dd16e71147c2ff52f2af89f91a65971046f726d8f89a2bae33b71deb028cadcbd18794eeb83e82b838a789d37638b5197d1

test:
  secret_key_base: 063af45ee1a0a25130e6f2b0d0ad5cd8fe9bce77e32f1240c76df66e273ff3b5b986358cd0847973c47db07aaa2cb712d1fe0f680791c656cd138e27eb5a4e2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
